---
- hosts: master
  become: yes

  vars_files:
    - vars/vars.yml

  pre_tasks:
    - name: Update apt cache if needed.
      apt: update_cache=yes cache_valid_time=3600

  handlers:
    - name: restart service
      service: name=service state=restarted

  tasks:
    - name: install prerequisites
      apt:
        pkg:
        - apt-transport-https
        - ca-certificates 
        - curl 
        - gnupg-agent
        - software-properties-common
    - name: add apt-key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
    - name: add docker repo
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
    - name: install docker 
      apt:
        name: 
        - docker-ce
        - docker-ce-cli
        - containerd.io
        update_cache: yes
        # notify: restart service
    - name: add userpermissions
      shell: "usermod -aG docker vagrant"
